#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
count=0
while [ $count -ne 11 ]
do
    if [ $count -eq 9 ]; then
	echo "Hi"
    else
	echo "Best School"
    fi
    ((count++))
done

